---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: testkubernets
  region: ap-south-1
availabilityZones: 
- ap-south-1a
- ap-south-1b
managedNodeGroups:
- name: on-demand
  labels:
    role: on-demand
  instanceType: t2.small
  desiredCapacity: 1
  volumeSize: 20