---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-testkubernetes
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: testkubernetes.5by1.com
    http:
      paths:
      - path: /
        backend:
          serviceName: testkubernetes
          servicePort: 8080
